name: Fineract Tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      IMAGE_NAME: fineract
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
      - name: Build the image
        run: ./gradlew --no-daemon --console=plain :fineract-provider:jibDockerBuild -Djib.to.image=$IMAGE_NAME -x test -x cucumber
      - name: Start the Fineract stack
        run: docker compose -f docker-compose-postgresql-test-activemq.yml up -d
      - name: Check the stack
        run: docker ps
      - name: Check health Manager
        run: curl -f -k --retry 60 --retry-all-errors --connect-timeout 30 --retry-delay 30 https://localhost:8443/fineract-provider/actuator/health
      - name: Execute tests
        env:
          BASE_URL: https://localhost:8443
          TEST_USERNAME: mifos
          TEST_PASSWORD: password
          TEST_STRONG_PASSWORD: A1b2c3d4e5f$
          TEST_TENANT_ID: default
          INITIALIZATION_ENABLED: true
          EVENT_VERIFICATION_ENABLED: true
          ACTIVEMQ_BROKER_URL: tcp://localhost:61616
          ACTIVEMQ_TOPIC_NAME: events
        run: ./gradlew --no-daemon --console=plain :fineract-e2e-tests-runner:cucumber --tags 'not @Skip' allureReport
